name: MFE Cloudfront Deployment

on:
  push:
    branches:
      - master
      - ednx-release/mango.nelp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ vars.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}

    - name: npm Install
      run: npm install
    - name: print env vars
      run: printenv
    - name: npm Build  # check env variables of repo.
      run: npm run build
      env:
        PUBLIC_PATH: /learning/
        APP_ID: learning
        MFE_CONFIG_API_URL: ${{ vars.MFE_CONFIG_API_URL }}
    - name: print html
      run: cat dist/index.html
    - name: Share artifact inside workflow
      uses: actions/upload-artifact@v3
      with:
        name: ${{ vars.MFE_NAME }}-dist-artifact
        path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # get build artifact
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ vars.MFE_NAME }}-dist-artifact
      - name: Display structure of downloaded files
        run: ls -R
      - name: Display structure of downloaded files
        run: pwd 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Copy build to s3
      - name: Deploy to S3
        run: |
          aws s3 sync . $S3_BUCKET
        env:
          S3_BUCKET: s3://${{ secrets.BUCKET_NAME }}
      # working-directory: ${{ vars.MFE_NAME }}-dist-artifact
